# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Thomas\Documents\maya\scripts\thomas_script\maya\scripts\rigToolKit\rigToolKit.ui'
#
# Created: Sun Aug 30 13:01:49 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

import Qt
from Qt import QtCore, QtGui, QtWidgets

class Ui_riggingToolKit(object):
    def setupUi(self, riggingToolKit):
        riggingToolKit.setObjectName("riggingToolKit")
        riggingToolKit.resize(380, 1473)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(riggingToolKit.sizePolicy().hasHeightForWidth())
        riggingToolKit.setSizePolicy(sizePolicy)
        riggingToolKit.setToolTip("")
        self.gridLayout = QtWidgets.QGridLayout(riggingToolKit)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.categorie_box = QtWidgets.QComboBox(riggingToolKit)
        self.categorie_box.setObjectName("categorie_box")
        self.categorie_box.addItem("")
        self.categorie_box.addItem("")
        self.categorie_box.addItem("")
        self.categorie_box.addItem("")
        self.categorie_box.addItem("")
        self.verticalLayout.addWidget(self.categorie_box)
        self.line_4 = QtWidgets.QFrame(riggingToolKit)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.BS_frame = QtWidgets.QWidget(riggingToolKit)
        self.BS_frame.setObjectName("BS_frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.BS_frame)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.BSconnect_groupBox = QtWidgets.QGroupBox(self.BS_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSconnect_groupBox.sizePolicy().hasHeightForWidth())
        self.BSconnect_groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.BSconnect_groupBox.setFont(font)
        self.BSconnect_groupBox.setObjectName("BSconnect_groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.BSconnect_groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.BSconnect_ctrl_axisLabel = QtWidgets.QLabel(self.BSconnect_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_ctrl_axisLabel.setFont(font)
        self.BSconnect_ctrl_axisLabel.setObjectName("BSconnect_ctrl_axisLabel")
        self.horizontalLayout_13.addWidget(self.BSconnect_ctrl_axisLabel)
        self.BSconnect_CtrlAxisX_checkBox = QtWidgets.QCheckBox(self.BSconnect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSconnect_CtrlAxisX_checkBox.sizePolicy().hasHeightForWidth())
        self.BSconnect_CtrlAxisX_checkBox.setSizePolicy(sizePolicy)
        self.BSconnect_CtrlAxisX_checkBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_CtrlAxisX_checkBox.setFont(font)
        self.BSconnect_CtrlAxisX_checkBox.setObjectName("BSconnect_CtrlAxisX_checkBox")
        self.horizontalLayout_13.addWidget(self.BSconnect_CtrlAxisX_checkBox)
        self.BSconnect_CtrlAxisY_checkBox = QtWidgets.QCheckBox(self.BSconnect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSconnect_CtrlAxisY_checkBox.sizePolicy().hasHeightForWidth())
        self.BSconnect_CtrlAxisY_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_CtrlAxisY_checkBox.setFont(font)
        self.BSconnect_CtrlAxisY_checkBox.setObjectName("BSconnect_CtrlAxisY_checkBox")
        self.horizontalLayout_13.addWidget(self.BSconnect_CtrlAxisY_checkBox)
        self.BSconnect_CtrlAxisZ_checkBox = QtWidgets.QCheckBox(self.BSconnect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSconnect_CtrlAxisZ_checkBox.sizePolicy().hasHeightForWidth())
        self.BSconnect_CtrlAxisZ_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_CtrlAxisZ_checkBox.setFont(font)
        self.BSconnect_CtrlAxisZ_checkBox.setObjectName("BSconnect_CtrlAxisZ_checkBox")
        self.horizontalLayout_13.addWidget(self.BSconnect_CtrlAxisZ_checkBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.gridLayout_9.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.BSconnect_clamp_checkBox = QtWidgets.QCheckBox(self.BSconnect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSconnect_clamp_checkBox.sizePolicy().hasHeightForWidth())
        self.BSconnect_clamp_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_clamp_checkBox.setFont(font)
        self.BSconnect_clamp_checkBox.setObjectName("BSconnect_clamp_checkBox")
        self.horizontalLayout_14.addWidget(self.BSconnect_clamp_checkBox)
        self.BSconnect_clamp_MinLabel = QtWidgets.QLabel(self.BSconnect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSconnect_clamp_MinLabel.sizePolicy().hasHeightForWidth())
        self.BSconnect_clamp_MinLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_clamp_MinLabel.setFont(font)
        self.BSconnect_clamp_MinLabel.setObjectName("BSconnect_clamp_MinLabel")
        self.horizontalLayout_14.addWidget(self.BSconnect_clamp_MinLabel)
        self.BSconnect_MinClamp_lineEdit = QtWidgets.QLineEdit(self.BSconnect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSconnect_MinClamp_lineEdit.sizePolicy().hasHeightForWidth())
        self.BSconnect_MinClamp_lineEdit.setSizePolicy(sizePolicy)
        self.BSconnect_MinClamp_lineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_MinClamp_lineEdit.setFont(font)
        self.BSconnect_MinClamp_lineEdit.setText("")
        self.BSconnect_MinClamp_lineEdit.setObjectName("BSconnect_MinClamp_lineEdit")
        self.horizontalLayout_14.addWidget(self.BSconnect_MinClamp_lineEdit)
        self.BSconnect_clamp_MaxLabel = QtWidgets.QLabel(self.BSconnect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSconnect_clamp_MaxLabel.sizePolicy().hasHeightForWidth())
        self.BSconnect_clamp_MaxLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_clamp_MaxLabel.setFont(font)
        self.BSconnect_clamp_MaxLabel.setObjectName("BSconnect_clamp_MaxLabel")
        self.horizontalLayout_14.addWidget(self.BSconnect_clamp_MaxLabel)
        self.BSconnect_MaxClamp_lineEdit = QtWidgets.QLineEdit(self.BSconnect_groupBox)
        self.BSconnect_MaxClamp_lineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.BSconnect_MaxClamp_lineEdit.setObjectName("BSconnect_MaxClamp_lineEdit")
        self.horizontalLayout_14.addWidget(self.BSconnect_MaxClamp_lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.gridLayout_9.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.BSconnect_MD_checkBox = QtWidgets.QCheckBox(self.BSconnect_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_MD_checkBox.setFont(font)
        self.BSconnect_MD_checkBox.setObjectName("BSconnect_MD_checkBox")
        self.horizontalLayout_15.addWidget(self.BSconnect_MD_checkBox)
        self.BSconnect_MD_valueLabel = QtWidgets.QLabel(self.BSconnect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSconnect_MD_valueLabel.sizePolicy().hasHeightForWidth())
        self.BSconnect_MD_valueLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_MD_valueLabel.setFont(font)
        self.BSconnect_MD_valueLabel.setObjectName("BSconnect_MD_valueLabel")
        self.horizontalLayout_15.addWidget(self.BSconnect_MD_valueLabel)
        self.BSconnect_MDvalue_lineEdit = QtWidgets.QLineEdit(self.BSconnect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSconnect_MDvalue_lineEdit.sizePolicy().hasHeightForWidth())
        self.BSconnect_MDvalue_lineEdit.setSizePolicy(sizePolicy)
        self.BSconnect_MDvalue_lineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.BSconnect_MDvalue_lineEdit.setObjectName("BSconnect_MDvalue_lineEdit")
        self.horizontalLayout_15.addWidget(self.BSconnect_MDvalue_lineEdit)
        self.BSconnect_MDmult_checkBox = QtWidgets.QCheckBox(self.BSconnect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSconnect_MDmult_checkBox.sizePolicy().hasHeightForWidth())
        self.BSconnect_MDmult_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_MDmult_checkBox.setFont(font)
        self.BSconnect_MDmult_checkBox.setObjectName("BSconnect_MDmult_checkBox")
        self.horizontalLayout_15.addWidget(self.BSconnect_MDmult_checkBox)
        self.BSconnect_MDdiv_checkBox = QtWidgets.QCheckBox(self.BSconnect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSconnect_MDdiv_checkBox.sizePolicy().hasHeightForWidth())
        self.BSconnect_MDdiv_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_MDdiv_checkBox.setFont(font)
        self.BSconnect_MDdiv_checkBox.setObjectName("BSconnect_MDdiv_checkBox")
        self.horizontalLayout_15.addWidget(self.BSconnect_MDdiv_checkBox)
        self.BSconnect_MDpow_checkBox = QtWidgets.QCheckBox(self.BSconnect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSconnect_MDpow_checkBox.sizePolicy().hasHeightForWidth())
        self.BSconnect_MDpow_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_MDpow_checkBox.setFont(font)
        self.BSconnect_MDpow_checkBox.setObjectName("BSconnect_MDpow_checkBox")
        self.horizontalLayout_15.addWidget(self.BSconnect_MDpow_checkBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.gridLayout_9.addLayout(self.horizontalLayout_15, 2, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.BSconnect_groupBox)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_9.addWidget(self.line_6, 3, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.BSconnect_Ctrl_listWidget = QtWidgets.QListWidget(self.BSconnect_groupBox)
        self.BSconnect_Ctrl_listWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.BSconnect_Ctrl_listWidget.setFont(font)
        self.BSconnect_Ctrl_listWidget.setObjectName("BSconnect_Ctrl_listWidget")
        self.horizontalLayout_18.addWidget(self.BSconnect_Ctrl_listWidget)
        self.BSconnect_BS_listWidget = QtWidgets.QListWidget(self.BSconnect_groupBox)
        self.BSconnect_BS_listWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.BSconnect_BS_listWidget.setObjectName("BSconnect_BS_listWidget")
        self.horizontalLayout_18.addWidget(self.BSconnect_BS_listWidget)
        self.gridLayout_9.addLayout(self.horizontalLayout_18, 4, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.BSconnect_ctrlLabel = QtWidgets.QLabel(self.BSconnect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSconnect_ctrlLabel.sizePolicy().hasHeightForWidth())
        self.BSconnect_ctrlLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_ctrlLabel.setFont(font)
        self.BSconnect_ctrlLabel.setObjectName("BSconnect_ctrlLabel")
        self.horizontalLayout_16.addWidget(self.BSconnect_ctrlLabel)
        self.BSconnect_BSLabel = QtWidgets.QLabel(self.BSconnect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSconnect_BSLabel.sizePolicy().hasHeightForWidth())
        self.BSconnect_BSLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_BSLabel.setFont(font)
        self.BSconnect_BSLabel.setObjectName("BSconnect_BSLabel")
        self.horizontalLayout_16.addWidget(self.BSconnect_BSLabel)
        self.gridLayout_9.addLayout(self.horizontalLayout_16, 5, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.BSconnect_AddCtrl_Button = QtWidgets.QPushButton(self.BSconnect_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_AddCtrl_Button.setFont(font)
        self.BSconnect_AddCtrl_Button.setObjectName("BSconnect_AddCtrl_Button")
        self.horizontalLayout_17.addWidget(self.BSconnect_AddCtrl_Button)
        self.BSconnect_ClearCtrl_Button = QtWidgets.QPushButton(self.BSconnect_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_ClearCtrl_Button.setFont(font)
        self.BSconnect_ClearCtrl_Button.setObjectName("BSconnect_ClearCtrl_Button")
        self.horizontalLayout_17.addWidget(self.BSconnect_ClearCtrl_Button)
        self.BSconnect_AddBS_Button = QtWidgets.QPushButton(self.BSconnect_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_AddBS_Button.setFont(font)
        self.BSconnect_AddBS_Button.setObjectName("BSconnect_AddBS_Button")
        self.horizontalLayout_17.addWidget(self.BSconnect_AddBS_Button)
        self.BSconnect_ClearBS_Button = QtWidgets.QPushButton(self.BSconnect_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_ClearBS_Button.setFont(font)
        self.BSconnect_ClearBS_Button.setObjectName("BSconnect_ClearBS_Button")
        self.horizontalLayout_17.addWidget(self.BSconnect_ClearBS_Button)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.BSconnect_Connect_Button = QtWidgets.QPushButton(self.BSconnect_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSconnect_Connect_Button.sizePolicy().hasHeightForWidth())
        self.BSconnect_Connect_Button.setSizePolicy(sizePolicy)
        self.BSconnect_Connect_Button.setMinimumSize(QtCore.QSize(0, 30))
        self.BSconnect_Connect_Button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSconnect_Connect_Button.setFont(font)
        self.BSconnect_Connect_Button.setObjectName("BSconnect_Connect_Button")
        self.verticalLayout_7.addWidget(self.BSconnect_Connect_Button)
        self.gridLayout_9.addLayout(self.verticalLayout_7, 6, 0, 1, 1)
        self.gridLayout_8.addWidget(self.BSconnect_groupBox, 4, 0, 1, 1)
        self.BScreate_groupBox = QtWidgets.QGroupBox(self.BS_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.BScreate_groupBox.setFont(font)
        self.BScreate_groupBox.setObjectName("BScreate_groupBox")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.BScreate_groupBox)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.BSname_label = QtWidgets.QLabel(self.BScreate_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BSname_label.sizePolicy().hasHeightForWidth())
        self.BSname_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.BSname_label.setFont(font)
        self.BSname_label.setObjectName("BSname_label")
        self.horizontalLayout_11.addWidget(self.BSname_label)
        self.curveBS_BSname_lineEdit = QtWidgets.QLineEdit(self.BScreate_groupBox)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.curveBS_BSname_lineEdit.setFont(font)
        self.curveBS_BSname_lineEdit.setObjectName("curveBS_BSname_lineEdit")
        self.horizontalLayout_11.addWidget(self.curveBS_BSname_lineEdit)
        self.gridLayout_10.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.curveBS_BScreate_button = QtWidgets.QPushButton(self.BScreate_groupBox)
        self.curveBS_BScreate_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.curveBS_BScreate_button.setFont(font)
        self.curveBS_BScreate_button.setObjectName("curveBS_BScreate_button")
        self.horizontalLayout_12.addWidget(self.curveBS_BScreate_button)
        self.curveBS_add_button = QtWidgets.QPushButton(self.BScreate_groupBox)
        self.curveBS_add_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.curveBS_add_button.setFont(font)
        self.curveBS_add_button.setObjectName("curveBS_add_button")
        self.horizontalLayout_12.addWidget(self.curveBS_add_button)
        self.gridLayout_10.addLayout(self.horizontalLayout_12, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.BScreate_groupBox, 0, 0, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.BS_frame)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_8.addWidget(self.line_12, 3, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.BS_frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_8.addWidget(self.line_3, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.BS_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sculptFromDico_button = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.sculptFromDico_button.setFont(font)
        self.sculptFromDico_button.setToolTip("")
        self.sculptFromDico_button.setObjectName("sculptFromDico_button")
        self.horizontalLayout_5.addWidget(self.sculptFromDico_button)
        self.invertShape_button = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.invertShape_button.setFont(font)
        self.invertShape_button.setToolTip("")
        self.invertShape_button.setObjectName("invertShape_button")
        self.horizontalLayout_5.addWidget(self.invertShape_button)
        self.gridLayout_8.addWidget(self.groupBox, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.BS_frame)
        self.CTRL_frame = QtWidgets.QWidget(riggingToolKit)
        self.CTRL_frame.setObjectName("CTRL_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.CTRL_frame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.line_5 = QtWidgets.QFrame(self.CTRL_frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_4.addWidget(self.line_5, 1, 0, 1, 1)
        self.ctrlVertice_groupBox = QtWidgets.QGroupBox(self.CTRL_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.ctrlVertice_groupBox.setFont(font)
        self.ctrlVertice_groupBox.setObjectName("ctrlVertice_groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ctrlVertice_groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.jntOnVert_jntName_label = QtWidgets.QLabel(self.ctrlVertice_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jntOnVert_jntName_label.sizePolicy().hasHeightForWidth())
        self.jntOnVert_jntName_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.jntOnVert_jntName_label.setFont(font)
        self.jntOnVert_jntName_label.setObjectName("jntOnVert_jntName_label")
        self.horizontalLayout_3.addWidget(self.jntOnVert_jntName_label)
        self.jntOnVert_jntName_lineEdit = QtWidgets.QLineEdit(self.ctrlVertice_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jntOnVert_jntName_lineEdit.sizePolicy().hasHeightForWidth())
        self.jntOnVert_jntName_lineEdit.setSizePolicy(sizePolicy)
        self.jntOnVert_jntName_lineEdit.setText("")
        self.jntOnVert_jntName_lineEdit.setObjectName("jntOnVert_jntName_lineEdit")
        self.horizontalLayout_3.addWidget(self.jntOnVert_jntName_lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addJoint_checkBox = QtWidgets.QCheckBox(self.ctrlVertice_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addJoint_checkBox.sizePolicy().hasHeightForWidth())
        self.addJoint_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.addJoint_checkBox.setFont(font)
        self.addJoint_checkBox.setObjectName("addJoint_checkBox")
        self.horizontalLayout_4.addWidget(self.addJoint_checkBox)
        self.ws_checkBox = QtWidgets.QCheckBox(self.ctrlVertice_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ws_checkBox.sizePolicy().hasHeightForWidth())
        self.ws_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.ws_checkBox.setFont(font)
        self.ws_checkBox.setObjectName("ws_checkBox")
        self.horizontalLayout_4.addWidget(self.ws_checkBox)
        self.mirrorX_checkBox = QtWidgets.QCheckBox(self.ctrlVertice_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mirrorX_checkBox.sizePolicy().hasHeightForWidth())
        self.mirrorX_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.mirrorX_checkBox.setFont(font)
        self.mirrorX_checkBox.setObjectName("mirrorX_checkBox")
        self.horizontalLayout_4.addWidget(self.mirrorX_checkBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.jntOnVert_create_button = QtWidgets.QPushButton(self.ctrlVertice_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jntOnVert_create_button.sizePolicy().hasHeightForWidth())
        self.jntOnVert_create_button.setSizePolicy(sizePolicy)
        self.jntOnVert_create_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.jntOnVert_create_button.setFont(font)
        self.jntOnVert_create_button.setObjectName("jntOnVert_create_button")
        self.verticalLayout_4.addWidget(self.jntOnVert_create_button)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.ctrlVertice_groupBox, 2, 0, 1, 1)
        self.ctrlCreate_groupBox = QtWidgets.QGroupBox(self.CTRL_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.ctrlCreate_groupBox.setFont(font)
        self.ctrlCreate_groupBox.setObjectName("ctrlCreate_groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.ctrlCreate_groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.circle_button = QtWidgets.QPushButton(self.ctrlCreate_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.circle_button.setFont(font)
        self.circle_button.setCheckable(True)
        self.circle_button.setDefault(False)
        self.circle_button.setFlat(False)
        self.circle_button.setObjectName("circle_button")
        self.horizontalLayout_2.addWidget(self.circle_button)
        self.sphere_button = QtWidgets.QPushButton(self.ctrlCreate_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.sphere_button.setFont(font)
        self.sphere_button.setCheckable(True)
        self.sphere_button.setObjectName("sphere_button")
        self.horizontalLayout_2.addWidget(self.sphere_button)
        self.square_button = QtWidgets.QPushButton(self.ctrlCreate_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.square_button.setFont(font)
        self.square_button.setCheckable(True)
        self.square_button.setObjectName("square_button")
        self.horizontalLayout_2.addWidget(self.square_button)
        self.cube_button = QtWidgets.QPushButton(self.ctrlCreate_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.cube_button.setFont(font)
        self.cube_button.setCheckable(True)
        self.cube_button.setObjectName("cube_button")
        self.horizontalLayout_2.addWidget(self.cube_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cylinder_button = QtWidgets.QPushButton(self.ctrlCreate_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.cylinder_button.setFont(font)
        self.cylinder_button.setCheckable(True)
        self.cylinder_button.setObjectName("cylinder_button")
        self.horizontalLayout_7.addWidget(self.cylinder_button)
        self.pushButton_5 = QtWidgets.QPushButton(self.ctrlCreate_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_7.addWidget(self.pushButton_5)
        self.diamond_button = QtWidgets.QPushButton(self.ctrlCreate_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.diamond_button.setFont(font)
        self.diamond_button.setCheckable(True)
        self.diamond_button.setObjectName("diamond_button")
        self.horizontalLayout_7.addWidget(self.diamond_button)
        self.root_button = QtWidgets.QPushButton(self.ctrlCreate_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.root_button.setFont(font)
        self.root_button.setCheckable(True)
        self.root_button.setObjectName("root_button")
        self.horizontalLayout_7.addWidget(self.root_button)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.gridLayout_5.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.createCtrl_label = QtWidgets.QLabel(self.ctrlCreate_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createCtrl_label.sizePolicy().hasHeightForWidth())
        self.createCtrl_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.createCtrl_label.setFont(font)
        self.createCtrl_label.setObjectName("createCtrl_label")
        self.horizontalLayout_6.addWidget(self.createCtrl_label)
        self.createCtrl_lineEdit = QtWidgets.QLineEdit(self.ctrlCreate_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createCtrl_lineEdit.sizePolicy().hasHeightForWidth())
        self.createCtrl_lineEdit.setSizePolicy(sizePolicy)
        self.createCtrl_lineEdit.setText("")
        self.createCtrl_lineEdit.setObjectName("createCtrl_lineEdit")
        self.horizontalLayout_6.addWidget(self.createCtrl_lineEdit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.createCtrl_button = QtWidgets.QPushButton(self.ctrlCreate_groupBox)
        self.createCtrl_button.setMinimumSize(QtCore.QSize(0, 30))
        self.createCtrl_button.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.createCtrl_button.setFont(font)
        self.createCtrl_button.setObjectName("createCtrl_button")
        self.verticalLayout_8.addWidget(self.createCtrl_button)
        self.gridLayout_5.addLayout(self.verticalLayout_8, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.ctrlCreate_groupBox, 0, 0, 1, 1)
        self.ctrlCurve_groupBox = QtWidgets.QGroupBox(self.CTRL_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.ctrlCurve_groupBox.setFont(font)
        self.ctrlCurve_groupBox.setObjectName("ctrlCurve_groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.ctrlCurve_groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.ctrlCurve_groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        self.curveBS_jntNum_spineBox = QtWidgets.QSpinBox(self.ctrlCurve_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.curveBS_jntNum_spineBox.sizePolicy().hasHeightForWidth())
        self.curveBS_jntNum_spineBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.curveBS_jntNum_spineBox.setFont(font)
        self.curveBS_jntNum_spineBox.setObjectName("curveBS_jntNum_spineBox")
        self.horizontalLayout_9.addWidget(self.curveBS_jntNum_spineBox)
        self.curveBS_followCurve_checkBox = QtWidgets.QCheckBox(self.ctrlCurve_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.curveBS_followCurve_checkBox.sizePolicy().hasHeightForWidth())
        self.curveBS_followCurve_checkBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.curveBS_followCurve_checkBox.setFont(font)
        self.curveBS_followCurve_checkBox.setObjectName("curveBS_followCurve_checkBox")
        self.horizontalLayout_9.addWidget(self.curveBS_followCurve_checkBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.curveBS_createJnt_button = QtWidgets.QPushButton(self.ctrlCurve_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.curveBS_createJnt_button.sizePolicy().hasHeightForWidth())
        self.curveBS_createJnt_button.setSizePolicy(sizePolicy)
        self.curveBS_createJnt_button.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.curveBS_createJnt_button.setFont(font)
        self.curveBS_createJnt_button.setObjectName("curveBS_createJnt_button")
        self.verticalLayout_6.addWidget(self.curveBS_createJnt_button)
        self.gridLayout_6.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.ctrlCurve_groupBox, 4, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.CTRL_frame)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_4.addWidget(self.line_7, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.CTRL_frame)
        self.curve_frame = QtWidgets.QWidget(riggingToolKit)
        self.curve_frame.setObjectName("curve_frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.curve_frame)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.convEdge_Button = QtWidgets.QPushButton(self.curve_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.convEdge_Button.sizePolicy().hasHeightForWidth())
        self.convEdge_Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.convEdge_Button.setFont(font)
        self.convEdge_Button.setObjectName("convEdge_Button")
        self.gridLayout_7.addWidget(self.convEdge_Button, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.curve_frame)
        self.cleanUp_frame = QtWidgets.QWidget(riggingToolKit)
        self.cleanUp_frame.setObjectName("cleanUp_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cleanUp_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.orig_button = QtWidgets.QPushButton(self.cleanUp_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orig_button.sizePolicy().hasHeightForWidth())
        self.orig_button.setSizePolicy(sizePolicy)
        self.orig_button.setObjectName("orig_button")
        self.verticalLayout_3.addWidget(self.orig_button)
        self.line_11 = QtWidgets.QFrame(self.cleanUp_frame)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_3.addWidget(self.line_11)
        self.frzTrs_delHist_button = QtWidgets.QPushButton(self.cleanUp_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frzTrs_delHist_button.sizePolicy().hasHeightForWidth())
        self.frzTrs_delHist_button.setSizePolicy(sizePolicy)
        self.frzTrs_delHist_button.setObjectName("frzTrs_delHist_button")
        self.verticalLayout_3.addWidget(self.frzTrs_delHist_button)
        self.line_10 = QtWidgets.QFrame(self.cleanUp_frame)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_3.addWidget(self.line_10)
        self.connectMod_button = QtWidgets.QPushButton(self.cleanUp_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectMod_button.sizePolicy().hasHeightForWidth())
        self.connectMod_button.setSizePolicy(sizePolicy)
        self.connectMod_button.setObjectName("connectMod_button")
        self.verticalLayout_3.addWidget(self.connectMod_button)
        self.line_8 = QtWidgets.QFrame(self.cleanUp_frame)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_3.addWidget(self.line_8)
        self.colorCtrl_button = QtWidgets.QPushButton(self.cleanUp_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorCtrl_button.sizePolicy().hasHeightForWidth())
        self.colorCtrl_button.setSizePolicy(sizePolicy)
        self.colorCtrl_button.setObjectName("colorCtrl_button")
        self.verticalLayout_3.addWidget(self.colorCtrl_button)
        self.line_9 = QtWidgets.QFrame(self.cleanUp_frame)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_3.addWidget(self.line_9)
        self.labelJnt_button = QtWidgets.QPushButton(self.cleanUp_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelJnt_button.sizePolicy().hasHeightForWidth())
        self.labelJnt_button.setSizePolicy(sizePolicy)
        self.labelJnt_button.setObjectName("labelJnt_button")
        self.verticalLayout_3.addWidget(self.labelJnt_button)
        self.verticalLayout.addWidget(self.cleanUp_frame)
        self.setup_frame = QtWidgets.QWidget(riggingToolKit)
        self.setup_frame.setObjectName("setup_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.setup_frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.blendLoc_button = QtWidgets.QPushButton(self.setup_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blendLoc_button.sizePolicy().hasHeightForWidth())
        self.blendLoc_button.setSizePolicy(sizePolicy)
        self.blendLoc_button.setObjectName("blendLoc_button")
        self.verticalLayout_2.addWidget(self.blendLoc_button)
        self.line = QtWidgets.QFrame(self.setup_frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.blendJnt_button = QtWidgets.QPushButton(self.setup_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blendJnt_button.sizePolicy().hasHeightForWidth())
        self.blendJnt_button.setSizePolicy(sizePolicy)
        self.blendJnt_button.setObjectName("blendJnt_button")
        self.horizontalLayout.addWidget(self.blendJnt_button)
        self.supportJnt_button = QtWidgets.QPushButton(self.setup_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.supportJnt_button.sizePolicy().hasHeightForWidth())
        self.supportJnt_button.setSizePolicy(sizePolicy)
        self.supportJnt_button.setObjectName("supportJnt_button")
        self.horizontalLayout.addWidget(self.supportJnt_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.setup_frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.twistJnt_button = QtWidgets.QPushButton(self.setup_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twistJnt_button.sizePolicy().hasHeightForWidth())
        self.twistJnt_button.setSizePolicy(sizePolicy)
        self.twistJnt_button.setObjectName("twistJnt_button")
        self.verticalLayout_2.addWidget(self.twistJnt_button)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.setup_frame)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.warningTextEdit = QtWidgets.QTextEdit(riggingToolKit)
        self.warningTextEdit.setMaximumSize(QtCore.QSize(16777215, 70))
        self.warningTextEdit.setObjectName("warningTextEdit")
        self.gridLayout.addWidget(self.warningTextEdit, 1, 0, 1, 1)

        self.retranslateUi(riggingToolKit)
        QtCore.QMetaObject.connectSlotsByName(riggingToolKit)

    def retranslateUi(self, riggingToolKit):
        riggingToolKit.setWindowTitle(Qt.QtCompat.translate("riggingToolKit", "Rigging Tool Kit - Thomas Lopez", None, -1))
        self.categorie_box.setCurrentText(Qt.QtCompat.translate("riggingToolKit", "Blendshapes", None, -1))
        self.categorie_box.setItemText(0, Qt.QtCompat.translate("riggingToolKit", "Blendshapes", None, -1))
        self.categorie_box.setItemText(1, Qt.QtCompat.translate("riggingToolKit", "Controllers", None, -1))
        self.categorie_box.setItemText(2, Qt.QtCompat.translate("riggingToolKit", "Curves", None, -1))
        self.categorie_box.setItemText(3, Qt.QtCompat.translate("riggingToolKit", "CleanUp", None, -1))
        self.categorie_box.setItemText(4, Qt.QtCompat.translate("riggingToolKit", "Setup", None, -1))
        self.BSconnect_groupBox.setTitle(Qt.QtCompat.translate("riggingToolKit", "Connect blendShape to controller", None, -1))
        self.BSconnect_ctrl_axisLabel.setText(Qt.QtCompat.translate("riggingToolKit", "Axis :", None, -1))
        self.BSconnect_CtrlAxisX_checkBox.setText(Qt.QtCompat.translate("riggingToolKit", "X", None, -1))
        self.BSconnect_CtrlAxisY_checkBox.setText(Qt.QtCompat.translate("riggingToolKit", "Y", None, -1))
        self.BSconnect_CtrlAxisZ_checkBox.setText(Qt.QtCompat.translate("riggingToolKit", "Z", None, -1))
        self.BSconnect_clamp_checkBox.setText(Qt.QtCompat.translate("riggingToolKit", "Clamp :", None, -1))
        self.BSconnect_clamp_MinLabel.setText(Qt.QtCompat.translate("riggingToolKit", "Min", None, -1))
        self.BSconnect_clamp_MaxLabel.setText(Qt.QtCompat.translate("riggingToolKit", "Max", None, -1))
        self.BSconnect_MD_checkBox.setText(Qt.QtCompat.translate("riggingToolKit", "MultiplyDivide :", None, -1))
        self.BSconnect_MD_valueLabel.setText(Qt.QtCompat.translate("riggingToolKit", "Value", None, -1))
        self.BSconnect_MDmult_checkBox.setText(Qt.QtCompat.translate("riggingToolKit", "Mult", None, -1))
        self.BSconnect_MDdiv_checkBox.setText(Qt.QtCompat.translate("riggingToolKit", "Div", None, -1))
        self.BSconnect_MDpow_checkBox.setText(Qt.QtCompat.translate("riggingToolKit", "Pow", None, -1))
        self.BSconnect_ctrlLabel.setText(Qt.QtCompat.translate("riggingToolKit", "Controllers             ", None, -1))
        self.BSconnect_BSLabel.setText(Qt.QtCompat.translate("riggingToolKit", " BlendShapes", None, -1))
        self.BSconnect_AddCtrl_Button.setText(Qt.QtCompat.translate("riggingToolKit", "Add Ctrl", None, -1))
        self.BSconnect_ClearCtrl_Button.setText(Qt.QtCompat.translate("riggingToolKit", "Clear", None, -1))
        self.BSconnect_AddBS_Button.setText(Qt.QtCompat.translate("riggingToolKit", "Add BS", None, -1))
        self.BSconnect_ClearBS_Button.setText(Qt.QtCompat.translate("riggingToolKit", "Clear", None, -1))
        self.BSconnect_Connect_Button.setText(Qt.QtCompat.translate("riggingToolKit", "Connect ctrl->blendshape", None, -1))
        self.BScreate_groupBox.setTitle(Qt.QtCompat.translate("riggingToolKit", "Blendshape node", None, -1))
        self.BSname_label.setText(Qt.QtCompat.translate("riggingToolKit", "BlendShape name :", None, -1))
        self.curveBS_BScreate_button.setText(Qt.QtCompat.translate("riggingToolKit", "Create blendshape node", None, -1))
        self.curveBS_add_button.setText(Qt.QtCompat.translate("riggingToolKit", "New blendshape", None, -1))
        self.groupBox.setTitle(Qt.QtCompat.translate("riggingToolKit", "Blendshape sculpting", None, -1))
        self.sculptFromDico_button.setText(Qt.QtCompat.translate("riggingToolKit", "Generate sculpt shapes", None, -1))
        self.invertShape_button.setText(Qt.QtCompat.translate("riggingToolKit", "Invert shape(s)", None, -1))
        self.ctrlVertice_groupBox.setTitle(Qt.QtCompat.translate("riggingToolKit", "Create controller on vertice", None, -1))
        self.jntOnVert_jntName_label.setText(Qt.QtCompat.translate("riggingToolKit", "Base name :", None, -1))
        self.addJoint_checkBox.setText(Qt.QtCompat.translate("riggingToolKit", "Create joint", None, -1))
        self.ws_checkBox.setText(Qt.QtCompat.translate("riggingToolKit", "World space", None, -1))
        self.mirrorX_checkBox.setText(Qt.QtCompat.translate("riggingToolKit", "Mirror X", None, -1))
        self.jntOnVert_create_button.setText(Qt.QtCompat.translate("riggingToolKit", "Create controller on vertex", None, -1))
        self.ctrlCreate_groupBox.setTitle(Qt.QtCompat.translate("riggingToolKit", "Controller shape", None, -1))
        self.circle_button.setText(Qt.QtCompat.translate("riggingToolKit", "Circle", None, -1))
        self.sphere_button.setText(Qt.QtCompat.translate("riggingToolKit", "Sphere", None, -1))
        self.square_button.setText(Qt.QtCompat.translate("riggingToolKit", "Square", None, -1))
        self.cube_button.setText(Qt.QtCompat.translate("riggingToolKit", "Cube", None, -1))
        self.cylinder_button.setText(Qt.QtCompat.translate("riggingToolKit", "Cylinder", None, -1))
        self.pushButton_5.setText(Qt.QtCompat.translate("riggingToolKit", "na", None, -1))
        self.diamond_button.setText(Qt.QtCompat.translate("riggingToolKit", "Diamond", None, -1))
        self.root_button.setText(Qt.QtCompat.translate("riggingToolKit", "Root", None, -1))
        self.createCtrl_label.setText(Qt.QtCompat.translate("riggingToolKit", "Controller name :", None, -1))
        self.createCtrl_button.setText(Qt.QtCompat.translate("riggingToolKit", "Create controller", None, -1))
        self.ctrlCurve_groupBox.setTitle(Qt.QtCompat.translate("riggingToolKit", "Create controller on curve", None, -1))
        self.label.setText(Qt.QtCompat.translate("riggingToolKit", "Number of joints :", None, -1))
        self.curveBS_followCurve_checkBox.setText(Qt.QtCompat.translate("riggingToolKit", "Follow", None, -1))
        self.curveBS_createJnt_button.setText(Qt.QtCompat.translate("riggingToolKit", "Create controller on curve", None, -1))
        self.convEdge_Button.setText(Qt.QtCompat.translate("riggingToolKit", "Convert edge selection to curve", None, -1))
        self.orig_button.setText(Qt.QtCompat.translate("riggingToolKit", "Create origin group on selected", None, -1))
        self.frzTrs_delHist_button.setText(Qt.QtCompat.translate("riggingToolKit", "Freeze transform + delete history", None, -1))
        self.connectMod_button.setToolTip(Qt.QtCompat.translate("riggingToolKit", "Select first the controler, the model grp and then the joint grp.", None, -1))
        self.connectMod_button.setText(Qt.QtCompat.translate("riggingToolKit", "Connect Model And Skeleton", None, -1))
        self.colorCtrl_button.setToolTip(Qt.QtCompat.translate("riggingToolKit", "Automatic.", None, -1))
        self.colorCtrl_button.setText(Qt.QtCompat.translate("riggingToolKit", "Add color to controllers", None, -1))
        self.labelJnt_button.setText(Qt.QtCompat.translate("riggingToolKit", "Label joints", None, -1))
        self.blendLoc_button.setToolTip(Qt.QtCompat.translate("riggingToolKit", "select one joint", None, -1))
        self.blendLoc_button.setText(Qt.QtCompat.translate("riggingToolKit", "Blended locator", None, -1))
        self.blendJnt_button.setToolTip(Qt.QtCompat.translate("riggingToolKit", "Select one or multiple target joint(s).", None, -1))
        self.blendJnt_button.setText(Qt.QtCompat.translate("riggingToolKit", "Blended Joint", None, -1))
        self.supportJnt_button.setToolTip(Qt.QtCompat.translate("riggingToolKit", "Select one or multiple target joint(s).", None, -1))
        self.supportJnt_button.setText(Qt.QtCompat.translate("riggingToolKit", "Support Joint", None, -1))
        self.twistJnt_button.setToolTip(Qt.QtCompat.translate("riggingToolKit", "Select taget joint and then parent joint.", None, -1))
        self.twistJnt_button.setText(Qt.QtCompat.translate("riggingToolKit", "Make Twist joints", None, -1))

