# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Thomas\git\thomas_script\thomas_script\maya\scripts\characterRigTool\characterRigTool.ui'
#
# Created: Tue Oct 11 11:26:15 2022
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

import Qt
from Qt import QtCore, QtGui, QtWidgets

class Ui_CharacterRigTool(object):
    def setupUi(self, CharacterRigTool):
        CharacterRigTool.setObjectName("CharacterRigTool")
        CharacterRigTool.resize(467, 631)
        self.gridLayout = QtWidgets.QGridLayout(CharacterRigTool)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rig_button = QtWidgets.QPushButton(CharacterRigTool)
        self.rig_button.setObjectName("rig_button")
        self.verticalLayout.addWidget(self.rig_button)
        self.skeleton_button = QtWidgets.QPushButton(CharacterRigTool)
        self.skeleton_button.setObjectName("skeleton_button")
        self.verticalLayout.addWidget(self.skeleton_button)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(CharacterRigTool)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textEdit = QtWidgets.QTextEdit(self.tab1)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_7.addWidget(self.textEdit)
        self.option_box = QtWidgets.QGroupBox(self.tab1)
        self.option_box.setObjectName("option_box")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.option_box)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.draw_button = QtWidgets.QPushButton(self.option_box)
        self.draw_button.setObjectName("draw_button")
        self.verticalLayout_2.addWidget(self.draw_button)
        self.update_button = QtWidgets.QPushButton(self.option_box)
        self.update_button.setObjectName("update_button")
        self.verticalLayout_2.addWidget(self.update_button)
        self.mirror_button = QtWidgets.QPushButton(self.option_box)
        self.mirror_button.setObjectName("mirror_button")
        self.verticalLayout_2.addWidget(self.mirror_button)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.torso_option = QtWidgets.QWidget(self.option_box)
        self.torso_option.setObjectName("torso_option")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.torso_option)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.section_count_label = QtWidgets.QLabel(self.torso_option)
        self.section_count_label.setObjectName("section_count_label")
        self.horizontalLayout.addWidget(self.section_count_label)
        self.section_count_spinBox = QtWidgets.QSpinBox(self.torso_option)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.section_count_spinBox.sizePolicy().hasHeightForWidth())
        self.section_count_spinBox.setSizePolicy(sizePolicy)
        self.section_count_spinBox.setProperty("value", 4)
        self.section_count_spinBox.setObjectName("section_count_spinBox")
        self.horizontalLayout.addWidget(self.section_count_spinBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_4.addWidget(self.torso_option, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.option_box)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.formLayout = QtWidgets.QFormLayout(self.tab2)
        self.formLayout.setObjectName("formLayout")
        self.asset_label = QtWidgets.QLabel(self.tab2)
        self.asset_label.setObjectName("asset_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.asset_label)
        self.assetName_txt = QtWidgets.QLineEdit(self.tab2)
        self.assetName_txt.setObjectName("assetName_txt")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.assetName_txt)
        self.ctrl_label = QtWidgets.QLabel(self.tab2)
        self.ctrl_label.setObjectName("ctrl_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ctrl_label)
        self.ctrl_txt = QtWidgets.QLineEdit(self.tab2)
        self.ctrl_txt.setObjectName("ctrl_txt")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ctrl_txt)
        self.jnt_label = QtWidgets.QLabel(self.tab2)
        self.jnt_label.setObjectName("jnt_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.jnt_label)
        self.jnt_txt = QtWidgets.QLineEdit(self.tab2)
        self.jnt_txt.setObjectName("jnt_txt")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.jnt_txt)
        self.center_label = QtWidgets.QLabel(self.tab2)
        self.center_label.setObjectName("center_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.center_label)
        self.center_txt = QtWidgets.QLineEdit(self.tab2)
        self.center_txt.setObjectName("center_txt")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.center_txt)
        self.right_label = QtWidgets.QLabel(self.tab2)
        self.right_label.setObjectName("right_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.right_label)
        self.right_txt = QtWidgets.QLineEdit(self.tab2)
        self.right_txt.setObjectName("right_txt")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.right_txt)
        self.left_label = QtWidgets.QLabel(self.tab2)
        self.left_label.setObjectName("left_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.left_label)
        self.left_txt = QtWidgets.QLineEdit(self.tab2)
        self.left_txt.setObjectName("left_txt")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.left_txt)
        self.c_color_label = QtWidgets.QLabel(self.tab2)
        self.c_color_label.setObjectName("c_color_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.c_color_label)
        self.c_color_combo = QtWidgets.QComboBox(self.tab2)
        self.c_color_combo.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.c_color_combo.setEditable(False)
        self.c_color_combo.setMaxVisibleItems(15)
        self.c_color_combo.setFrame(True)
        self.c_color_combo.setObjectName("c_color_combo")
        self.c_color_combo.addItem("")
        self.c_color_combo.addItem("")
        self.c_color_combo.addItem("")
        self.c_color_combo.addItem("")
        self.c_color_combo.addItem("")
        self.c_color_combo.addItem("")
        self.c_color_combo.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.c_color_combo)
        self.r_color_label = QtWidgets.QLabel(self.tab2)
        self.r_color_label.setObjectName("r_color_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.r_color_label)
        self.c_color_combo_2 = QtWidgets.QComboBox(self.tab2)
        self.c_color_combo_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.c_color_combo_2.setEditable(False)
        self.c_color_combo_2.setMaxVisibleItems(15)
        self.c_color_combo_2.setFrame(True)
        self.c_color_combo_2.setObjectName("c_color_combo_2")
        self.c_color_combo_2.addItem("")
        self.c_color_combo_2.addItem("")
        self.c_color_combo_2.addItem("")
        self.c_color_combo_2.addItem("")
        self.c_color_combo_2.addItem("")
        self.c_color_combo_2.addItem("")
        self.c_color_combo_2.addItem("")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.c_color_combo_2)
        self.l_color_label = QtWidgets.QLabel(self.tab2)
        self.l_color_label.setObjectName("l_color_label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.l_color_label)
        self.c_color_combo_3 = QtWidgets.QComboBox(self.tab2)
        self.c_color_combo_3.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.c_color_combo_3.setEditable(False)
        self.c_color_combo_3.setMaxVisibleItems(15)
        self.c_color_combo_3.setFrame(True)
        self.c_color_combo_3.setObjectName("c_color_combo_3")
        self.c_color_combo_3.addItem("")
        self.c_color_combo_3.addItem("")
        self.c_color_combo_3.addItem("")
        self.c_color_combo_3.addItem("")
        self.c_color_combo_3.addItem("")
        self.c_color_combo_3.addItem("")
        self.c_color_combo_3.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.c_color_combo_3)
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.RTB_button = QtWidgets.QPushButton(self.tab3)
        self.RTB_button.setObjectName("RTB_button")
        self.verticalLayout_4.addWidget(self.RTB_button)
        self.matConstr_button = QtWidgets.QPushButton(self.tab3)
        self.matConstr_button.setObjectName("matConstr_button")
        self.verticalLayout_4.addWidget(self.matConstr_button)
        self.Ribbon_button = QtWidgets.QPushButton(self.tab3)
        self.Ribbon_button.setObjectName("Ribbon_button")
        self.verticalLayout_4.addWidget(self.Ribbon_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(CharacterRigTool)
        self.tabWidget.setCurrentIndex(0)
        self.c_color_combo.setCurrentIndex(5)
        self.c_color_combo_2.setCurrentIndex(1)
        self.c_color_combo_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CharacterRigTool)

    def retranslateUi(self, CharacterRigTool):
        CharacterRigTool.setWindowTitle(Qt.QtCompat.translate("CharacterRigTool", "Widget", None, -1))
        self.rig_button.setText(Qt.QtCompat.translate("CharacterRigTool", "Generate Rig", None, -1))
        self.skeleton_button.setText(Qt.QtCompat.translate("CharacterRigTool", "Skeleton preview", None, -1))
        self.option_box.setTitle(Qt.QtCompat.translate("CharacterRigTool", "Options", None, -1))
        self.draw_button.setText(Qt.QtCompat.translate("CharacterRigTool", "Draw Guide", None, -1))
        self.update_button.setText(Qt.QtCompat.translate("CharacterRigTool", "Update Guide", None, -1))
        self.mirror_button.setText(Qt.QtCompat.translate("CharacterRigTool", "Mirror Guide", None, -1))
        self.section_count_label.setText(Qt.QtCompat.translate("CharacterRigTool", "Section count :", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), Qt.QtCompat.translate("CharacterRigTool", "Guide/Rig", None, -1))
        self.asset_label.setText(Qt.QtCompat.translate("CharacterRigTool", "Asset name :", None, -1))
        self.ctrl_label.setText(Qt.QtCompat.translate("CharacterRigTool", "Controller suffix :", None, -1))
        self.ctrl_txt.setText(Qt.QtCompat.translate("CharacterRigTool", "_ctrl", None, -1))
        self.jnt_label.setText(Qt.QtCompat.translate("CharacterRigTool", "Joints suffix :", None, -1))
        self.jnt_txt.setText(Qt.QtCompat.translate("CharacterRigTool", "_jnt", None, -1))
        self.center_label.setText(Qt.QtCompat.translate("CharacterRigTool", "Center prefix :", None, -1))
        self.center_txt.setText(Qt.QtCompat.translate("CharacterRigTool", "_C", None, -1))
        self.right_label.setText(Qt.QtCompat.translate("CharacterRigTool", "Right prefix :", None, -1))
        self.right_txt.setText(Qt.QtCompat.translate("CharacterRigTool", "_R", None, -1))
        self.left_label.setText(Qt.QtCompat.translate("CharacterRigTool", "Left prefix :", None, -1))
        self.left_txt.setText(Qt.QtCompat.translate("CharacterRigTool", "_L", None, -1))
        self.c_color_label.setText(Qt.QtCompat.translate("CharacterRigTool", "Center color :", None, -1))
        self.c_color_combo.setCurrentText(Qt.QtCompat.translate("CharacterRigTool", "Yellow", None, -1))
        self.c_color_combo.setItemText(0, Qt.QtCompat.translate("CharacterRigTool", "Blue", None, -1))
        self.c_color_combo.setItemText(1, Qt.QtCompat.translate("CharacterRigTool", "Red", None, -1))
        self.c_color_combo.setItemText(2, Qt.QtCompat.translate("CharacterRigTool", "Green", None, -1))
        self.c_color_combo.setItemText(3, Qt.QtCompat.translate("CharacterRigTool", "Light Blue", None, -1))
        self.c_color_combo.setItemText(4, Qt.QtCompat.translate("CharacterRigTool", "Light Red", None, -1))
        self.c_color_combo.setItemText(5, Qt.QtCompat.translate("CharacterRigTool", "Yellow", None, -1))
        self.c_color_combo.setItemText(6, Qt.QtCompat.translate("CharacterRigTool", "Purple", None, -1))
        self.r_color_label.setText(Qt.QtCompat.translate("CharacterRigTool", "Right color :", None, -1))
        self.c_color_combo_2.setCurrentText(Qt.QtCompat.translate("CharacterRigTool", "Red", None, -1))
        self.c_color_combo_2.setItemText(0, Qt.QtCompat.translate("CharacterRigTool", "Blue", None, -1))
        self.c_color_combo_2.setItemText(1, Qt.QtCompat.translate("CharacterRigTool", "Red", None, -1))
        self.c_color_combo_2.setItemText(2, Qt.QtCompat.translate("CharacterRigTool", "Green", None, -1))
        self.c_color_combo_2.setItemText(3, Qt.QtCompat.translate("CharacterRigTool", "Light Blue", None, -1))
        self.c_color_combo_2.setItemText(4, Qt.QtCompat.translate("CharacterRigTool", "Light Red", None, -1))
        self.c_color_combo_2.setItemText(5, Qt.QtCompat.translate("CharacterRigTool", "Yellow", None, -1))
        self.c_color_combo_2.setItemText(6, Qt.QtCompat.translate("CharacterRigTool", "Purple", None, -1))
        self.l_color_label.setText(Qt.QtCompat.translate("CharacterRigTool", "Left color :", None, -1))
        self.c_color_combo_3.setCurrentText(Qt.QtCompat.translate("CharacterRigTool", "Blue", None, -1))
        self.c_color_combo_3.setItemText(0, Qt.QtCompat.translate("CharacterRigTool", "Blue", None, -1))
        self.c_color_combo_3.setItemText(1, Qt.QtCompat.translate("CharacterRigTool", "Red", None, -1))
        self.c_color_combo_3.setItemText(2, Qt.QtCompat.translate("CharacterRigTool", "Green", None, -1))
        self.c_color_combo_3.setItemText(3, Qt.QtCompat.translate("CharacterRigTool", "Light Blue", None, -1))
        self.c_color_combo_3.setItemText(4, Qt.QtCompat.translate("CharacterRigTool", "Light Red", None, -1))
        self.c_color_combo_3.setItemText(5, Qt.QtCompat.translate("CharacterRigTool", "Yellow", None, -1))
        self.c_color_combo_3.setItemText(6, Qt.QtCompat.translate("CharacterRigTool", "Purple", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), Qt.QtCompat.translate("CharacterRigTool", "Settings", None, -1))
        self.RTB_button.setText(Qt.QtCompat.translate("CharacterRigTool", "Open Rigging Tool Box", None, -1))
        self.matConstr_button.setText(Qt.QtCompat.translate("CharacterRigTool", "Matrice Constraint", None, -1))
        self.Ribbon_button.setText(Qt.QtCompat.translate("CharacterRigTool", "Ribbon setup", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), Qt.QtCompat.translate("CharacterRigTool", "Tools", None, -1))

